### ISSUE TITLE
Force dark mode toggle not working

### ISSUE THREAD

**Issue by micahlt** [Scratch-Client-4/itchy-ionic#26]
There is a "force dark mode" toggle button in the settings tab that should allow web users and those without an Android 10+ device to enable Itchy's dark theme via a CSS class.  However, I haven't been able to get this to work.  Help is appreciated!

**Comment by locness3** [comment]
Well, this part of the CSS makes no sense :
https://github.com/Scratch-Client-4/itchy-ionic/blob/4f6a5284cd81a90a95104f380743453552528edc/src/theme/variables.css#L70

**Comment by micahlt** [comment]
How?  It's fully relevant.  If the user's device detects dark theme or the user manually turns on the `.dark` class via the toggle, then the dark mode vars take effect.  Right?

**Comment by locness3** [comment]
Well, you can't combine media queries and selectors.

**Comment by micahlt** [comment]
Oh wow, lol, I'm an idiot.  Gosh.  Yeah, we should fix that.

**Comment by locness3** [comment]
I think the best thing to do is to use JS to apply the dark class based on the media query, otherwise we'd need to duplicate the CSS. See https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries

(btw, what happened to following BEM? it should be smth like `theme--dark`)

**Comment by locness3** [comment]
> I think the best thing to do is to use JS to apply the dark class based on the media query, otherwise we'd need to duplicate the CSS. See https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries

So I had tried to do this, however I need to interact with the Vue instance from within the MediaQueryListener, but the `this` in the MQL function refers to the MQL, and not the Vue instance. Any attempts to pass the Vue instance to the function would result in the app crashing to a full white - or black - screen.

I'll have to try it again, but I may just use a CSS preprocessor to duplicate the vars to both the media query and the class selector.

**Comment by locness3** [comment]
I decided to use the trick [here](https://stackoverflow.com/questions/40338877/css-scss-media-query-or-class) : use inverse logic, instead of applying the dark style when the media matches "dark" or the dark class is present, make dark styles the default and apply light colors if the media matches "light" and the dark class is not present. However I don't have the light colors for ios/md at hand.
But anyways, I wanted to use LESS but couldn't get the LESS file to be properly loaded, it would give me an error i couldn't find a solution to.

So I think I should just do it in plain CSS, but **I'd still need the light md and ios colors**. Or, I should try in JS with the capacitor-dark-mode thing.

But it's been a whole day since I'm on this issue. I ran way too many times into the app just not building, because... I don't know, I don't speak Webpack errors. I guess it's my fault if it breaks, but I have no idea what I did. Google didn't help. And I wasted too much time just trying to get the tools to properly work. The tech stack used here just breaks every other time, at least for me. It gets in my way every small issue I try to work on. I wouldn't believe you use it without these kind of problems.

I'm done releasing my frustration on the tools that I probably just don't know how to use.

**Comment by micahlt** [comment]
Not gonna lie, I totally feel you here.  Webpack is a bloated mess and it's almost impossible to debug.  Generally I can figure out the errors with some googling - would you be willing to provide a screenshot?  I may have encountered the same error before.

Thanks for your contribution by the way ☺️

**Comment by locness3** [comment]
> Webpack is a bloated mess

It's overcomplex, yes. Just like the Ionic+Vue+Capacitor (let's say IVC) stack itself.

If you want my opinion, I think "native" Android development is easier and better : makes a faster and smaller app, and it's the real proper way of doing things. It may seem scary at first, but I've done some little things (I still have a lot to learn), and I find that Java is not hard if coming from JavaScript, and Android Studio offers a lot of coding assistance (really).

Making an android native Scratch app is on my mental hardly ever done ideas list, but it's pretty high considering the trouble we're having with IVC.

**Comment by micahlt** [comment]
_Oh my_... I'll be honest, I'm not going to move development platforms again, especially to Java or Kotlin, whatever you were going to use.  Sorry, I really can't see myself using a low-level language.

**Comment by locness3** [comment]
Java is low-level now? It's not even compiled... But Android Studio manages the whole thing anyways.

**Comment by locness3** [comment]
Anyways, might want to remove that dark theme checkbox to not give a bad impression.

**Comment by locness3** [comment]
> Anyways, might want to remove that dark theme checkbox for now. 

Please do so. @micahlt
