### ISSUE TITLE
[bug] Can't install

### ISSUE THREAD

**Issue by VelocityDesign** [Scratch-Client-4/itchy-ionic#47]
Continued from comment section.
Here's a capture:
![Screenshot_20220226-114557.png](https://user-images.githubusercontent.com/24457862/155854900-63b792c2-2518-4330-a904-234e776c5e6e.mp4)

**Comment by VelocityDesign** [comment]
Latest nightly works. I forgot to uninstall the app before installing. However, the issue remains with the stable version.

**Comment by micahlt** [comment]
The reason for this is that I'm not bumping the version of the app in the Gradle file every single time I provide an APK, forcing users to uninstall before updating.  This is bad UX at the moment, but it won't be the case when we release the app since there will be routine version bumps.  

> However, the issue remains with the stable version. 

Are you saying that even after uninstalling another version you're still not able to install the latest stable (0.9.5)?

**Comment by micahlt** [comment]
Interesting... well for now stay on the latest nightly and I'll make a new release once #46 is merged.  I'm going to close this for now, but if you have trouble installing 0.9.7 (I'll shoot you a comment when it's released) then feel free to reopen it.
